fabiangreffrath/crispy-doom

codeblocks/README
codeblocks/config.h
codeblocks/crispy.workspace
codeblocks/doom.cbp
codeblocks/game-res.rc
codeblocks/heretic.cbp
codeblocks/hexen.cbp
codeblocks/libopl.cbp
codeblocks/libpcsound.cbp
codeblocks/server.cbp
codeblocks/setup-res.rc
codeblocks/setup.cbp
codeblocks/strife.cbp

Updated CodeBlocks project files to Crispy version 3.5. Fixed some missing files and changed setup executable name to "crispy-doom-setup.exe".

Updated CodeBlocks project files

---

codeblocks/doom.cbp

Added `p_blockmap.c` file to `Doom` project.

CodeBlocks project update

---

src/doom/d_main.c
src/doom/p_mobj.c
src/net_common.c
src/setup/multiplayer.c

Let's make deathmatches crispier...

Add Deathmatch 3.0

---

src/doom/r_main.c
src/doom/r_things.c

Don't forget about multiplayer games.

Play back demos with interpolation even if the menu is open, pt. 3

---

src/doom/p_inter.c

Allows DeHackEd mods to customize item drops better.

Check MF_DROPPED for all ammo and weapons.

---

src/doom/am_map.c

Thanks @JNechaevsky for the suggestion and testing, fixes #405

zoom and move Automap with the mouse (wheel)

---

src/doom/r_things.c

Taken from Russian Doom, resp. MBF, thanks @JNechaevsky.

apply some clipping optimizations

---

src/heretic/mn_menu.c

This the very first implementation of Crispness menu for Crispy Heretic. 
@fabiangreffrath, please remember, it was your idea! :no_mouth:

Heretic: first implementation of Crispness menu

---

src/heretic/g_game.c

See https://github.com/fabiangreffrath/crispy-doom/commit/44eff6997521fac16223015da4e6531c09718dc3#commitcomment-38003638

Fix out of bounds array access

---

src/heretic/mn_menu.c

Done the fashion it was in Doom, had to introduce an extra variable though to make it work.

Heretic slider values + high mouse sensitivity support

---

src/heretic/d_main.c
src/heretic/g_game.c

See https://www.doomworld.com/forum/post/2119904 for discussion.

Heretic: Make demoextend and shortticfix the default

---

README.md

Inspired by a friend of mine's extreme confusion and attempts to compile from source on Ubuntu 18.04 since they did not realize it was in apt.

Add Ubuntu/Debian install instructions

---

src/crispy.h
src/doom/d_main.c
src/doom/d_player.h
src/doom/g_game.c
src/doom/hu_stuff.c
src/doom/m_crispy.c
src/doom/m_crispy.h
src/doom/m_menu.c
src/doom/p_user.c
src/m_config.c
src/setup/compatibility.c

Thanks Looper for the repeated suggestion. ;)

add a "use" button timer, apparently useful for practicing speed-running

---

src/heretic/s_sound.c
src/heretic/sounds.c
src/heretic/sounds.h

Thanks to Dwars for the suggestion.

Heretic: support dedicated music tracks for each map

---

src/heretic/mn_menu.c

Add restart level/demo + next level button functionality

---

CMakeLists.txt
cmake/config.h.cin

Adapted from how options were done in https://github.com/coelckers/prboom-plus/blob/master/prboom2/CMakeLists.txt#L173 and https://github.com/coelckers/prboom-plus/blob/master/prboom2/cmake/config.h.cin#L37

Add CMake toggle for truecolor.

---

src/doom/r_data.c

As discussed in: https://github.com/fabiangreffrath/crispy-doom/issues/740

Fix potentially incorrect translucency

---

src/doom/d_main.c
src/heretic/d_main.c
src/hexen/h2_main.c
src/m_config.c
src/m_config.h
src/strife/d_main.c

Closes #749, thanks @OpenRift412 for the suggestion and @rfomin for
the prior implementation in Woof!.

support autoload directories for PWADs

---

src/i_sdlmusic.c
src/i_winmusic.c

Fix playing music other than in MUS/MIDI format (on Windows)

---

src/hexen/am_map.c
src/hexen/f_finale.c
src/hexen/h2_main.c
src/hexen/h2def.h
src/hexen/in_lude.c
src/hexen/mn_menu.c
src/hexen/r_draw.c
src/hexen/r_main.c
src/hexen/r_plane.c
src/hexen/sb_bar.c
src/v_video.c
src/v_video.h

Hopefully done? Most of it is copy and paste from Heretic, with the exception of the widescreen asset support. If my approach to that is deemed okay I'll port it over to Heretic so there's parity between the two games.

Add widescreen to Hexen

---

README.md

Meant to provide this earlier but I was beaten to the punch. If you're happy with the longer description feel free to leave as is.

Update pistolstart/wandstart in README

---

src/heretic/r_draw.c
src/heretic/r_plane.c
src/hexen/r_draw.c
src/hexen/r_local.h
src/hexen/r_plane.c
src/hexen/r_segs.c
src/hexen/r_things.c

Add tutti-frutti fix which also happens to remove the 128 pixel post limit. (Fixes #859)
Add support for DeePsea tall patches.
I'm not especially confident that I properly implemented this so if you see anything funny or wrong, don't hesitate to say so!

Heretic and Hexen column drawing updates

---

src/hexen/g_game.c
src/hexen/h2_main.c
src/hexen/h2def.h
src/hexen/mn_menu.c
src/hexen/p_anim.c
src/hexen/p_floor.c
src/hexen/p_mobj.c
src/hexen/p_setup.c
src/hexen/p_user.c
src/hexen/po_man.c
src/hexen/r_bsp.c
src/hexen/r_local.h
src/hexen/r_main.c
src/hexen/r_plane.c
src/hexen/r_segs.c
src/hexen/r_things.c
src/setup/compatibility.c

Hexen uncapped framerate

---

src/heretic/d_main.c
src/hexen/h2_main.c

Please confirm that I didn't mess up anything in the load order. We could probably move this code into a common function but I'm not entirely certain where it would live. (`src/w_main.c` perhaps?)
Fixes #864.

Heretic/Hexen: Support PWAD autoload directories

---

src/hexen/g_game.c
src/setup/keyboard.c

This seemed to be pretty straightforward to implement, but since I'm a first timer, I have no idea if I'm doing any of this right so I gladly expect feedback, regardless of whether it's positive or negative.
Closes #885 .
All actual credit goes to [kraflab](https://github.com/kraflab), since I only ported their implementation for Heretic with some minor changes.

Hexen autorun/novert

---

README.md

@fabiangreffrath @JNechaevsky Here's a first pass at the changelog. Hopefully I didn't miss too much.

Update README changelog for next release

---

src/doom/am_map.c
src/heretic/am_map.c
src/heretic/am_map.h
src/hexen/am_map.c
src/hexen/am_map.h
src/m_config.c
src/m_controls.c
src/m_controls.h
src/setup/mouse.c

- Doom: Map panning is now the same speed in low and high res.
- Add dedicated mouse button bindings for zoom in/out, follow mode and max zoom out.
- Heretic/Hexen: Add mouse panning for automap.
- Allow keyboard panning of automap in overlay mode. Fixes #872.

Various automap improvements

---

src/doom/am_map.c
src/heretic/am_map.c
src/hexen/am_map.c

As suggested in https://github.com/fabiangreffrath/crispy-doom/commit/2a0f5330a5e128ce96cfba85657cf59c1eed0aef#commitcomment-76953603.

Apply various interpolations for automap

---

src/doom/am_map.c
src/heretic/am_data.h
src/heretic/am_map.c
src/hexen/am_data.h
src/hexen/am_map.c

📝 Notes: 
* Heretic: fixed incorrect keys coloring on easiest skill.
* Heretic and Hexen: preserved Raven code styling with extra spaces between variables.
* Corrected my comment about stable player arrow: it was not about interpolation, it was "keep arrow on the center of the map without unnecessary coords transferring".

Switch automap to FRACTOMAPBITS coordinate system

---

src/heretic/am_map.c
src/hexen/am_map.c

Thanks @rzhxiii for pointing out (https://github.com/fabiangreffrath/crispy-doom/issues/910).

Heretic & Hexen: fix automap background parallax

---

src/doom/am_map.c
src/heretic/am_map.c
src/hexen/am_map.c

Thanks @rfomin for composing it into one PR: https://github.com/fabiangreffrath/woof/pull/659
Zooming isn't touched _(pshaw!)_. Current problem: panning by mouse not working at all, some help could be very appreciated.

Interpolate automap drawing and panning

---

.github/workflows/release.yml
CHANGELOG.md
pkg/win32/GNUmakefile

Fix #919 
Tested on my fork: https://github.com/rfomin/chocolate-doom/releases/tag/crispy-doom-5.12.6

implement release build automation

---

src/doom/am_map.c
src/heretic/am_map.c
src/hexen/am_map.c

Solves [this issue](https://www.doomworld.com/forum/post/2540576).

Fix automap line jitter in low res mode

---

src/hexen/mn_menu.c

Hexen: generate a default save slot name

---

src/hexen/h2def.h
src/hexen/mn_menu.c
src/hexen/sv_save.c

Fixes #935.
This seemed to be easier than I initially thought it would be, so I would appreciate a sanity check.

Hexen: Delete savegames from menu

---

src/heretic/doomdef.h
src/heretic/mn_menu.c
src/heretic/p_saveg.c

Submitting the Heretic implementation of this for review. Once we get everything in a happy state I'll port it over to Hexen.

Heretic: Support 8 pages of saves

---

src/crispy.h
src/doom/d_main.c
src/doom/m_crispy.c
src/doom/m_menu.c
src/doom/m_menu.h
src/heretic/d_main.c
src/heretic/mn_menu.c
src/hexen/h2_main.c
src/hexen/mn_menu.c
src/m_config.c
src/setup/compatibility.c

The main purpose of this PR is to add the Default Difficulty option to Heretic and Hexen. I also tweaked the Doom implementation so that the setting gets applied immediately. (Previously it only appeared to take effect after restarting the program.) Also did some minor OCD clean-up so the config variable is listed alphabetically in the code.

Expand and improve Default Difficulty option

---

src/doom/r_bsp.c
src/heretic/r_bsp.c
src/hexen/r_bsp.c

No interpolation for instant moving sectors

---

src/CMakeLists.txt
src/Makefile.am
src/i_glob.c
src/i_oplmusic.c
src/i_sdlmusic.c
src/i_sound.c
src/i_sound.h
src/i_winmusic.c
src/m_config.c
src/m_misc.c
src/m_misc.h
src/midifallback.c
src/midifallback.h
src/midifile.c
src/midifile.h
src/setup/sound.c

The mp3/ogg/tracker music will not work due to the introduction of `mus_win_module`. Should I fix this in a separate PR? Should we make a Woof-like system with dynamic module change in `I_RegisterMusic` if the track is non-MIDI?

winmm merge

---

src/hexen/am_map.c
src/hexen/h2_main.c
src/hexen/h2def.h
src/hexen/sb_bar.c
src/hexen/textdefs.h

Essentially a quick copy-and-paste of the Heretic implementation. I left the references to  the coordinate widget in because I figured we might possibly implement that at some point.

hexen: Add SHOWFPS cheat

---

src/heretic/CMakeLists.txt
src/heretic/Makefile.am
src/heretic/doomdata.h
src/heretic/p_extnodes.c
src/heretic/p_extnodes.h
src/heretic/p_setup.c
src/heretic/r_local.h

Loads a new map from Heretic project: https://doomuniverse.com/topic/102/the-heretic-project-quest-name-pending

Implement DeePBSP and ZDBSP nodes support in Crispy Heretic

---

.github/workflows/msys2.yml

* Rename release.yml->msys2.yml
* Run msys2.yml on push/pull request for master branch
* Upload artifacts

Update CI workflow

---

src/i_timer.c
src/i_timer.h
src/i_video.c

Use improved frame rate limiting routine

---

src/strife/st_stuff.c

Fixes https://github.com/fabiangreffrath/crispy-doom/issues/1028

strife: Handle cheats when using inventory keys

---

src/hexen/p_pspr.c

hexen: Don't align swiping weapons

---

docs/changelog-history.md
docs/cheats.md
docs/crispness.md
docs/faq.md
docs/params.md
src/doom/d_main.c
src/heretic/d_main.c
src/hexen/h2_main.c
src/strife/d_main.c

This started as simple proofreading but I expanded the scope a bit to correct a few assorted doc and man page issues that I noticed. Did I miss anything?

Docs update

---

src/i_winmusic.c
src/m_config.c
src/setup/sound.c

win midi: Use Crispier default setting

---

src/doom/r_plane.c
src/heretic/r_plane.c
src/hexen/r_plane.c
src/strife/r_plane.c

* Applied: https://github.com/fabiangreffrath/woof/pull/1074
* For all four games.
* As small diff as possible.

Add half pixel correction to fix distortion

---

src/doom/r_bmaps.c

exclude TNT brightmaps when not using tnt.wad

---

src/doom/p_mobj.c

fix mid-air speed boost when using noclip cheat

---

src/doom/p_mobj.h

Yeah, that Vanilla comment is worth preserving, rather funny :)

Preserved historical vanilla Hmm??? comment

---

src/doom/r_plane.c
src/doom/r_sky.c

Like this @kitchen-ace? Fixes #1092

stretch short skies only

---

CHANGELOG.md
README.md
docs/changelog-history.md

Hello Fabian, it's nice to be back even if just for a very short time. Until then, take care of yourselves

update personal info & links to profile

---

src/doom/p_map.c
src/heretic/p_map.c

below OR above, not before OF above :)

Fixed another p_map.c comment typo

---

src/hexen/p_setup.c
src/hexen/po_man.c
src/hexen/r_bsp.c
src/hexen/r_local.h
src/hexen/r_segs.c

Improve Hexen polyobject interpolation

---

src/doom/am_map.c
src/doom/f_finale.c
src/doom/hu_stuff.c
src/doom/r_data.c
src/doom/r_main.c
src/doom/r_state.h
src/heretic/am_map.c
src/heretic/r_data.c
src/heretic/r_local.h
src/heretic/r_plane.c
src/hexen/am_map.c
src/hexen/r_data.c
src/hexen/r_local.h
src/hexen/r_plane.c

As requested in https://github.com/fabiangreffrath/crispy-doom/pull/1145#issuecomment-1923207320.

Update truecolor code

---

src/hexen/r_plane.c

My [ancient implementation](https://github.com/JNechaevsky/international-doom/pull/68/commits/0d7144a252943d936f1b24a47c53c1d6fd1fb6f3) from ~2018 was pretty goofy and I even wasn't willing to suggest it, as it have a lot of flaws. This one is much simpler and cleaner, few remarks should be made though:
* It's not really about uncapped frame rate, it will work same even in capped 35 fps mode, but to keep things vanilla way, smoothing will be applied only in uncapped mode.
* Despite of `<< 6` multiplier is a magic number, it was heavily verified to represent original speeds (yep, they can be different in `MAPINFO`), and after running two game windows for about ~10 minutes, notable sky texture parts are still on sync. Thanks to @kitchen-ace for making this experiment as well!
* Please note, …

Hexen: interpolate sky scrolling

---

src/crispy.c

A small quality of life change that adjusts aspect ratio by default.

Aspect ratio to match screen by default

---

src/doom/d_pwad.c

don't let sideloaded PWADs replace default Doom 2 artwork

---

src/doom/g_game.c

Close file stream in G_WriteLevelStat function.

Fix -levelstat command

---

src/doom/p_user.c
src/hexen/p_user.c

sidemove was not correct added, when in midair

FIX: Strafe in mid air was not strafe but forward / backward

---

src/heretic/r_data.c
src/heretic/r_local.h
src/heretic/r_plane.c
src/hexen/r_data.c
src/hexen/r_local.h
src/hexen/r_plane.c

Make Hexen and Heretic sky tutti-frutti fix work for any sky height

---

src/m_config.c
src/setup/mouse.c
src/strife/g_game.c

Related Issue:
None 
Activating the quick reverse key functionality in Strife and adding also the mouse key for it.

Strife: Adding quick reverse functionality

---

src/doom/am_map.c
src/doom/p_tick.c
src/doom/p_tick.h

They are very handy when cleaning up a large map. Should they be added for Heretic, Hexen and Strife too?

Add IDDST, IDDKT, IDDIT cheats from Woof

---

src/doom/am_map.c
src/doom/d_main.c
src/heretic/am_map.c
src/heretic/d_main.c
src/hexen/am_map.c
src/hexen/h2_main.c
src/i_video.c
src/i_video.h
src/strife/am_map.c
src/strife/d_main.c

It turns out that automap mouse panning was a little broken after the fast polling changes. (Whoops!) This PR fixes that, and also address the jittering issue pointed out by #1297. (Thanks to @jiffygist!)

Automap mouse panning improvements

---

src/doom/r_data.c
src/heretic/f_finale.c
src/v_video.c
src/v_video.h

Fix #1316 
It works, but maybe I changed too many things.

Support wide RAW images from new "Heretic + Hexen" release
