src/doom/d_player.h
src/doom/p_user.c
src/doom/r_main.c

This patch gets rid of the unpleasant jerkiness when you have freelook or weapon recoil enabled with >35 framecap.

Smooth freelook and weapon recoil

---

src/hexen/in_lude.c

Fixed bug of unhires'ed b/w patch INTERPIC, which is used as background between episodes.
Tested (and found) in my project, and now it is working fine.

[Hexen] Update in_lude.c

---

src/heretic/p_setup.c
src/heretic/r_bsp.c
src/heretic/r_local.h
src/heretic/r_plane.c
src/heretic/r_segs.c
src/heretic/r_things.c

Values are verified with current Crispy Doom.
Game/timedemos working fine. Coding style preserved (well, for 99%).
This will not change anything visually, but makes a green light for further limit removing changes.

Heretic: upgrade renderer to use 32-bit integer math

---

src/doom/st_stuff.c

During a demo playback, this prevents the screen from flashing (like when the player picks up an item or gets hurt) when the help screen or crispness menu is open.
Edit: This applies to viewing the help screen or crispness menu when the game is paused too.

Stop palette changes from happening when in help screen or crispness menu

---

src/doom/p_enemy.c

When an Arch-Vile resurrects a mirrored corpse, the enemy stays mirrored, resulting in some funky-looking moonwalking.
This fix works and is simple, but the ideal fix would be to unflip the sprite after the resurrection animation completes.

Fix resurrections of mirrored corpses staying mirrored

---

src/doom/p_setup.c

Remove missing things check since the player start checks were added to Chocolate Doom

---

src/doom/info.h
src/doom/p_map.c
src/doom/p_mobj.c
src/doom/p_mobj.h
src/doom/p_setup.c

@Zodomaniac: This will help mitigate the issue you once reported when
both mouselook and direct aiming are enabled and you miss some obvious
targets, like e.g. Romero's head on a stick.
I am not merging this, yet, because I am still unsure in two questions:
- Should it be (critical->freeaim == FREEAIM_DIRECT) or
(critical->freeaim == FREEAIM_BOTH), i.e. do we have to consider
only the direct aiming case or also the mixed case with autoaiming?
- Should it get applies only to PTR_ShootTraverse() or also to
PTR_AimTraverse(), i.e. do we have to consider only shooting (and
laser aiming, that is) or also aiming. This is probably connected to
the former question, though.

calculate the things' actual height from the spawnstate's first sprite

---

src/setup/joystick.c

Since jumping can be enabled in Doom the joystick jump button should be assignable in the setup program.

Allow joybjump to be assigned for Doom

---

src/doom/d_main.c

This reverts the following commit, which drew the automap beneath the
bezel for decreased screen sizes. I am not sure anymore why I would
have ever wanted it this way:
https://github.com/fabiangreffrath/crispy-doom/commit/8acfb0321592a32d031bf26b49f6403dc58696ca
Fixes #446.
Also, moving the call to `AM_Drawer()` past `R_DrawViewBorder()` fixes #340.

in automap overlay mode, draw automap on top of everything

---

src/doom/st_lib.c
src/doom/st_stuff.c

Fixes #407, thanks @JNechaevsky.
This calls for more optimizations regarding Crispy HUD rendering.

only redraw status bar numbers if necessary

---

src/doom/m_menu.c

override savegame name if it already starts with a map identifier

---

src/doom/d_main.c
src/doom/f_finale.c
src/doom/m_menu.c
src/doom/r_data.c
src/v_video.c
src/v_video.h

This makes Crispy resemble Vanilla more closely again, even without
minor cosmetic alterations that are nevertheless visible at first
sight. And since there won't be a menu switch for this...

remove shadowed menu and text drawing

---

src/i_sdlsound.c

Here's a crispy version of https://github.com/coelckers/prboom-plus/pull/42 .
Note that the upsampling used when there is no `libresample` and `SDL_ConvertAudio()` isn't used is slightly worse than in the prboom version, as I didn't include the linear interpolation and just left the zero-order hold that was there originally.

Enable loading 16 bit RIFF wavs in .wads.

---

src/i_sdlsound.c

Looks like there was a little bug in parsing 16-bit audio data, since I didn't notice the call to `ExpandSoundData()` in `CacheSFX()` shifts the address of `data` by 8 bytes before using it.
This fixes that.

Fix 16 bit audio files shifted by 8 bytes.

---

src/heretic/d_main.c

Bind `crispy_smoothscaling` which can be set in Crispness menu.

Heretic: bind `crispy_smoothscaling`

---

src/doom/m_menu.c
src/i_video.c

as widescreen rendering only makes sense if certain pixel aspect ratio is enforced, i.e. aspect ratio correction is enabled.

No aspect ratio correction-no widescreen rendering

---

src/i_video.c

after it gets forcefully disabled with aspect ratio correction set to 'none'

Remember widescreen setting

---

src/doom/m_crispy.c

as pistol firing sound played upon any (including futile) attempt to manipulate the Crispness menu item is much louder and oofs can barely be heard.

Oofs...removed from Crispness menu

---

src/doom/p_extsaveg.c

to preserve savegame header compatibility across forks that might have different names, e.g. "so-doom"

Explicitly write "crispy-doom" to extended savegame header

---

src/doom/m_crispy.c

The whole menu string should be read as a whole sentence making sense.
"Widescreen rendering: Compact" reads kinda: WIDE and COMPACT - WTF, mutually excluding paragraphs?!
So I propose Widescreen setting be Off or On, with HUD specifics in brackets, there's enough space for that.

Improved understanding of widescreen rendering

---

src/doom/m_crispy.c

as the closing one doesn't fit in the menu, and the opening one resembles C in (Compact HUD)

Removed brackets from widescreen menu items

---

src/i_video.c

as otherwise the messed-up HUD is shown during wipe screen on 16:10 displays.

Default widescreen resolution 2 b the narrowest

---

src/i_video.c

Create widgets if `SDL_GetCurrentDisplayMode` fails, e.g. when launching a map from command line on Windows.
@fabiangreffrath , you could've been busy and have forgotten about it, so here it is)

Patch to fix #533 by @fabiangreffrath

---

src/heretic/g_game.c
src/m_config.c
src/setup/keyboard.c

Adds the novert toggle key to heretic.
I tried to get the hud message working with heretic, but I wasn't sure how to make it actually show up on the screen, although I was setting the player message field similarly to how it works in the doom file. It wasn't worth the effort to me to dig into it more, so I settled for just the sound to indicate the switch.
If the hud message is a requirement then probably someone with more understanding of the logic there would need to set it up.

Add novert toggle to heretic

---

src/heretic/g_game.c

Copies over the run input handling from doom:
If "always run" is on, and the user holds down the run key, they will walk instead.
I will add the autorun toggle key support as well, but thought I'd get these aligned first.
I also didn't add the other uses for the `speedkeydown` method yet for heretic. If you'd rather I set that stuff up in a batch, let me know.

Always Run + Run = Walk (heretic)

---

src/setup/compatibility.c

When you currently run "crispy-setup" for heretic, it resets all the crispy options to their defaults (stats, the new secret message, etc).
This patch binds those variables for heretic in `setup/compatibility` (it looks like this is what it does for doom, so I just duplicated that behaviour), which lets them keep their values when running the setup.

Prevent heretic crispy settings from resetting in setup

---

src/heretic/g_game.c
src/setup/keyboard.c

Adds the autorun toggle feature to heretic. Follows the same pattern as with the novert toggle key.
I rearranged the setup menu slightly. Previously I had moved novert out of the doom-specific list to a shared list with heretic, but I realized heretic didn't actually have the "movement" section so it looked a bit off. I moved the doom line back into its section and made a separate heretic one so it looks cleaner in the setup program.
This is also one of the tasks in the "various" list from https://github.com/fabiangreffrath/crispy-doom/issues/240, fyi @JNechaevsky

Add autorun toggle key to heretic

---

src/heretic/in_lude.c

And also don't pad the minutes with 0s if there's no hour, so an exit
time of one minute will display as "1:00". This is the same way Doom
displays the time.
(Also I wanted an easy commit to see if I could make PRs with both Crispy and Chocolate.)

Crispy-Heretic: Always display seconds in intermission time

---

src/heretic/in_lude.c

For maps in episodes 4 and above, the level time is not normally shown.
There's plenty of space for it though. I've double-checked that this
doesn't desync multi-level demos.

Heretic: Always show level time in extended maps

---

src/hexen/g_game.c
src/hexen/h2_main.c

Might as well be consistent to Hexen, even though Crispy Hexen isn't
really supported right now.

Hexen: Make demoextend and shortticfix the default

---

src/heretic/f_finale.c
src/heretic/g_game.c

Fixes two cases:
* Intermission screen (`in_lude.c`) - [screenshot](https://user-images.githubusercontent.com/21193394/81106444-49e8b600-8f1e-11ea-9e22-01b635d58c0b.png)
* Finale screen (`f_finale.c`) - [screenshot](https://user-images.githubusercontent.com/21193394/81106495-62f16700-8f1e-11ea-9dda-87bd6d0855be.png)
These changes are small and I believe there is no need to add `// [crispy]` comments.

Heretic: clear centered message on intermission and finale screens

---

src/heretic/p_user.c

Fixes remaining of centered message was not cleared from border and bezel ([screenshot](https://user-images.githubusercontent.com/21193394/81115701-cedacc00-8f2c-11ea-8fb4-e3eda634055b.png)).

Heretic: clear centered message from border and bezel

---

src/heretic/r_draw.c
src/hexen/r_draw.c

Properly refresh top border's background in hires mode. Fixes this ([screenshot](https://user-images.githubusercontent.com/21193394/81145162-6b798a00-8f7e-11ea-9639-60b10a1b462d.png)).

Heretic & Hexen: fix top border refresh

---

src/doom/am_map.c

Only with extended map colours on. This aids visibility and opens the
possibility to have a more saturated red for walls again.
As discussed in https://github.com/fabiangreffrath/crispy-doom/issues/613

Make keyed doors flash on the automap

---

src/doom/am_map.c

Changes the wall colours to be closer to vanilla, and changes the key
wall colours slightly to differentiate them a bit more. With the key
linedefs now flashing, I think it's easy enough to spot them on the map.

Change extended map colours to be closer to vanilla's

---

src/doom/deh_thing.c
src/doom/info.h
src/doom/p_inter.c
src/doom/p_setup.c

Support the same dehacked Thing field as Doom Retro.
"Dropped item" will allow to specify the Thing Id to be spawned after
the Thing dies.
It's a generalization of the same behavior that in Doom vanilla is
hardcoded for MT_WOLFSS, MT_POSSESSED, MT_SHOTGUY and MT_CHAINGUY.
Thanks for the hint :P  
https://www.doomworld.com/forum/topic/115638-dehextra-discussion-split-from-pr-umapinfo-thread/?page=2&tab=comments#comment-2156303

Add "Dropped Item" support

---

src/doom/deh_thing.c

This was apparently an oversight that was recently corrected in Doom Retro by brad already, sorry.
https://github.com/bradharding/doomretro/commit/cd62a1c2349e90bdbe7cde78dc5a193b95e24168

Make "Dropped item" 1-based in DEH, not 0-based

---

src/doom/deh_thing.c
src/doom/info.h
src/doom/p_enemy.c
src/doom/p_setup.c

This will add the following dehacked fields for Things:
* Melee threshold: distance to switch from missile to melee attack
* Max target range: Maximum distance range to start shooting (zero for unlimited)
* Min missile chance: Minimum chance for firing a missile
Based on old changes done in prboom-plus branch by Graf:
https://github.com/coelckers/prboom-plus/commit/f5f8dea10bbb6ae20796c4459b39e68e8f4b6586
In addition the following field is added (as FRACUNIT-based scalar instead of being a flag):
* Missile chance multiplier: multiplier that factors the likelihood of shooting missiles. 65536 being the normal firing chance, lower values will proportionally increase the firing chance, while higher values will reduce it.
Discussed in Doomworld thread: …

Generalizations dehardcoding some vanilla behavior

---

src/heretic/sb_bar.c

This restructures the cheat code handling to check for skill level and
netgames on a per-cheat basis. It's a little redundant but the least-
intrusive way I could think to do it.
Cheats enabled in Black Plague Possesses Thee (Heretic's Nightmare):
ENGAGExy: warp to level
NOISE: sound debug info
Cheats enabled in BPPT as well as netgames:
TICKER: show ticks-per-frame counter
SHOWFPS: show FPS counter (crispy specific cheat)
I don't see how the latter two could affect netgames at all, but it's
not something I've tested.
Partially resolves #634

Heretic: Allow ENGAGExy cheat (and some others) in Nightmare

---

src/heretic/g_game.c

PRBoom+ has a `-levelstat` option which causes some details about a map to be printed to `levelstat.txt` when the player gets to the exit. This data is printed for each map, so the levelstat file will have one line for each map completed.
Example: `E1M1 - 0:06.86 (0:06)  K: 4/22  I: 0/4  S: 1/4`
This file tracks kills / secrets for max validation, tracks times level by level for movie runs, and shows the map exit. In addition to general use by runners, this data helps with automation for DSDA.
This tooling is currently missing for heretic.
---
This PR adds the levelstat command line option and file for heretic. I'll be happy to add this for doom as well if it's approved. The format is identical to the one used by PRBoom+. One thing missing is, as far as I can tell, the total time across …

Add levelstat option (heretic)

---

README.md
src/doom/g_game.c

See https://github.com/fabiangreffrath/crispy-doom/pull/643 for context (heretic).
This is the same thing for doom.
We have access to the total time now, so handling has been added for that.
Additionally we need to handle the case of doom 2 style (MAP15) vs doom 1 style (E1M1) level names.

Add levelstat to doom

---

src/heretic/doomdef.h
src/heretic/g_game.c

Adds total time tracking for heretic and incorporates the full implementation of levelstat from the doom PR (https://github.com/fabiangreffrath/crispy-doom/pull/644).

Track heretic total time for levelstat

---

src/heretic/in_lude.c

Adds total elapsed time to the intermission screen for heretic. I had to adjust the positioning of the current time to make some room.
From e4 onwards, heretic has a "now entering" text underneath the time, which doesn't leave much room. It fits but I don't know if we want to adjust any of the other text on the screen vertically to give more space between things.

Add total time to heretic intermission

---

src/heretic/doomdef.h
src/heretic/g_game.c
src/heretic/in_lude.c

Took a bit of trial and error in the intermission logic but this seems to work fine. Checked waiting for the tallies at the intermission screen as well as skipping through it, and checked e1 and e4 (since they have different intermission formats).

Add final intermission to heretic episodes

---

src/doom/d_main.c

Fixes errors caused by Sigil being loaded playing Chex Quest.

Only load Sigil when gameversion is Ultimate Doom

---

src/crispy.h
src/doom/d_main.c
src/doom/g_game.c
src/heretic/d_main.c
src/heretic/g_game.c

Per #654, submitting this PR which implements a basic "pistol start" command line option. When this option has been specified, the player's health and inventory are reset to game start or resurrection values. This option is disabled when recording a demo, playing back a demo or when in a network game.
These changes seem too simple (probably missing some edge cases!) so I am interested in any suggestions on how to make this more robust and worthwhile.

Add pistol/wand start command line option

---

src/crispy.h
src/doom/f_finale.c
src/doom/m_crispy.c
src/doom/m_crispy.h
src/doom/m_menu.c
src/doom/st_stuff.c
src/i_video.c
src/v_video.c

Here's a crispy version of https://github.com/chocolate-doom/chocolate-doom/pull/1317 .
This version adds support for widescreen huds from https://forum.zdoom.org/viewtopic.php?f=19&t=37960 , and the Doom widescreen modding assets from https://bethesda.net/en/game/doom-widescreen-mods , as long as they're placed in a pwad and converted to native Doom graphics format.

Support widescreen assets.

---

src/doom/f_finale.c
src/doom/g_game.c
src/doom/p_enemy.c
src/doom/wi_stuff.c

With this change, both NRFTL and The Masterlevels get full special
treatment - even during network games, demo recording and playback.
This includes level transitions to the secret maps and back, finale
text screens, par times etc.
Users who insist on the pure Vanilla experience that was applied in
previous releases or who need it to properly play back demos recorded
with a previous release may want to simply rename their NERVE.WAD PWAD
file and explicitly load it on the command line.
Thanks Coincident and Keyboard_Doomer for input from the DSDA
community!

apply special treatment for NRFTL and Masterlevels - even during demos

---

src/doom/r_main.c
src/doom/st_stuff.c
src/doom/st_stuff.h

Just fixing a bug I saw reported at https://www.doomworld.com/forum/topic/67168-crispy-doom-592-update-sep-22-2020/?do=findComment&comment=2207398 .

Fix bezel crash.

---

src/heretic/doomdef.h
src/heretic/dstrings.h
src/heretic/p_enemy.c
src/heretic/p_inter.c
src/heretic/r_main.c
src/heretic/sb_bar.c

- show weapon pickup messages even in cooperative multiplayer (where weapons stay)
- implement additional cheat codes (ported from Crispy Doom), one of which requires the weapon pickup string table added for the above
Why in the same pull request? I didn't realize that the pull request gets automatically updated if I merge changes from another branch to the master in _my own fork_ of the repo, first time using github after all as mentioned on DW. Apologies.

Show weapon pickup messages in cooperative multiplayer and implement additional cheat codes

---

src/doom/d_main.c

This fixes automap remainings after ending the game in overlaid automap mode:
Initial discussion: https://github.com/JNechaevsky/russian-doom/issues/225

Clear overlaid automap remainings

---

src/doom/am_map.c

This PR implements smooth rotation in automap rotate mode. 
Tested with capped framerate as well as with `-fliplevels`, everything fine.

Implement smooth automap rotation

---

src/doom/r_data.c

This restores the old behavior of using a TRANMAP if one is present in a loaded wad.
As a use case, the dehacked mod I'm working on includes a table made with additive blending, and the effects/missiles are designed with this in mind. I've also made an additive table for my Doom autoloads, it looks quite nice:
It also seemed like a good idea to validate the table's size, since this is effectively a modding-specific feature. Please let me know if you don't find it necessary.

Allow use of custom translucency maps (again).

---

src/doom/m_menu.c

Palette changes can make the Crispness menu background look quite strange. E.G. Back to Saturn X, which replaces several of the browns with new shades:
A palette-correct version can be provided by a PWAD autoload to cover these cases, or mods with changed palettes can include the replacement themselves. Any 64x64 flat will do:
(>64 row flats like Heretic/Hexen use should also be fine, we only care about the first 64.)

Customizable Crispness menu background.

---

src/doom/d_englsh.h
src/doom/deh_bexstr.c
src/doom/p_inter.c

This simply makes the beta scepter & bible (from MBF extensions) gettable without a P_SpecialThing error. The items themselves do nothing (although they already have COUNTITEM so they can work as extra collectibles). Obviously if there are no sprites for them they'll still error out on spawn.
Pickup messages are provided based on ZDoom's keynames (though the text uses release DOOM grammar). They can be replaced through BEX.

Allow the beta bonus items to be picked up.

---

src/doom/m_menu.c

Update the menu item in accordance with the #769 fix.

Remove colored corpses from menu

---

src/doom/g_game.c
src/doom/m_menu.c
src/doom/p_doors.c
src/doom/p_inter.c
src/doom/p_mobj.c
src/doom/p_user.c
src/doom/s_sound.c
src/doom/s_sound.h
src/doom/sounds.c
src/doom/sounds.h
src/doom/wi_stuff.c

A few new sound effects that will only be used if the relevant sound lumps exist. Perfect for modders or autoload goodies.
Gameplay sounds:
* PLJUMP: Player jumping.
* PLLAND: Player hard landing, as in Hexen. (Replaces DSOOF at higher velocity.)
* LOCKED: Trying a locked door. (Replaces DSOOF.)
* KEYUP: Picking up a key. (Replaces DSITEMUP.)
Menu sounds:
* MNUOPN: Opening a menu.
* MNUCLS: Closing the menu.
* MNUACT: Activating a submenu.
* MNUBAK: Returning to a parent menu.
* MNUMOV: Moving the cursor.
* MNUSLI: Moving a slider, window size, detail level, etc.
* MNUERR: Errors. (Quicksaving when not ingame, etc.)
So this is a slightly large addition. I've added two small functions to s_sound to keep changes concise with no deletions. (Fingers crossed.) Comments cross the 80chr wall in …

Add some (optional) extra sounds.

---

src/doom/g_game.c
src/m_config.c
src/m_controls.c
src/m_controls.h
src/setup/keyboard.c
src/setup/mainmenu.c

Split from #799.
Implemented as a simple toggle using 'singletics' (employed by '-timedemo'). Default key set to <kbd>Numpad+</kbd>.
The speed of fast-forward will be dependent on the user's VSync setting. 
With VSync ON the speed will depend on the display's refresh rate, e.g. 170% speed at 60Hz, 200% at 70hz, 400% at 144hz.
With VSync OFF fast-forward will go as fast as possible.

Demo fast-forward

---

src/doom/g_game.c

Adaptation of demo pausing code and associated demo sync safeguards from prboom-plus.
Uses existing 'demostarttic' instead of prb+'s 'basetic'.
Special thanks to kraflab for his help.
Resolves #463.

Enable demo pause

---

src/hexen/h2_main.c
src/hexen/mn_menu.c
src/hexen/r_data.c

... and I definitely mean basic:
I wasn't able to successfully change the text color using `dp_translation`. Most `CR_` indices yielded dark text, not colored as expected. Any ideas? Hexen PLAYPAL shenanigans?
Other than that everything seems to be functioning as expected.

Implement basic Hexen Crispness menu

---

README.md
src/crispy.h
src/doom/d_main.c
src/doom/g_game.c
src/doom/p_inter.c
src/heretic/am_map.c
src/heretic/d_main.c
src/heretic/g_game.c
src/heretic/p_enemy.c
src/heretic/p_inter.c
src/heretic/p_mobj.c
src/hexen/d_net.c
src/hexen/g_game.c
src/hexen/h2_main.c
src/hexen/h2def.h
src/hexen/p_enemy.c
src/hexen/p_inter.c
src/hexen/p_mobj.c
src/strife/d_main.c
src/strife/g_game.c
src/strife/p_inter.c

Implements #790. Additional command line parameters for customizing difficulty as per https://doomwiki.org/wiki/Skill_level.
**Doom**
- `-doubleammo` double ammo pickup rate. Demo incompatible.
**Heretic**
- `-fast` fast monsters. Demo incompatible.
- `-moreammo` 50% more ammo pickup rate. Demo incompatible.
- `-autohealth` automatic use of Quartz flasks and Mystic urns.
- `-keysloc` keys are displayed on the automap.
**Hexen**
- `-fast` fast monsters. Demo incompatible.
- `-moremana` 50% more mana pickup rate. Demo incompatible.
- `-autohealth` automatic use of Quartz flasks and Mystic urns.
**Strife**
- `-doubleammo` double ammo pickup rate. Demo incompatible.

Custom difficulty parameters

---

src/setup/compatibility.c

Sorry to have overlooked this previously. There are a handful of other variables that setup and Heretic/Hexen have binding conflicts over: there are the a11y variables (which I don't think are used yet in Heretic/Hexen), a few y-axis mouse configs and also `video_display`. If you want I can try to address those here as well.
Fixes #838.

Bind additional valid variables in setup

---

src/d_loop.c
src/i_input.c
src/i_timer.c
src/i_timer.h
src/i_video.c

As discussed here: [https://www.doomworld.com/forum/topic/127475-sdl2-v-sync-and-mouse-movement/](url)
The idea behind my fix is to adjust each mouse read in proportion to how late we are sampling the mouse, and then to add the excess to the next tic's mouse values. It is essentially linear interpolation for the mouse movement.
I had to move the `fractionaltic` calculation to `NetUpdate` in order for it to be recent enough to be effective for this correction. Otherwise I need to get a local value in the `SmoothMouse` function. I think the main reason is that `NET_SV_Run` takes a not insignificant amount of time, and you can end up rolling over to the new tic while running that function. In that case `fractionaltic` might be some high value around 0.9.

Implement mouse smoothing when running uncapped

---

src/doom/r_plane.c
src/doom/r_segs.c
src/doom/r_things.c

This simplifies b-map lightning. `colormaps` is all we need to use a full brightness.
Testing map updated with floor and wall textures in different light levels: [plasmaguns.zip](https://github.com/fabiangreffrath/crispy-doom/files/8659441/plasmaguns.zip)

Simplify b-map lighting

---

src/v_video.c

Fixes #890.
On a side note, I was wondering why `V_DrawTLPatch()` and `V_DrawAltTLPatch()` are doing the exact same thing. Turns out, they're not supposed to. :) I'll fix that upstream in Chocolate.

Make V_DrawAltTLPatch() widescreen-compatible

---

src/heretic/r_main.c
src/hexen/r_main.c

I removed the round down of `screenheight` to the nearest power of 2, which fixes #896. I have tested all combinations of aspect ratio, resolution and view size and have confirmed there are no glitches with the drawing of the view border. So it appears that the rounding is not necessary.
I also fixed a copy-and-paste error where I accidentally used the Heretic status bar height instead of the Hexen. Luckily this error didn't cause any problems for the majority of aspect ratios and view sizes.

Heretic/Hexen: Minor update for player view

---

src/heretic/g_game.c
src/hexen/g_game.c

When recording demos, mouselook movements are now mapped to the "look" variable also used for keyboard look. Compared to normal gameplay, the mouselook fidelity is reduced. This is similar to how turning resolution is lower when recording a vanilla demo.  Furthermore, the amount of travel in a tic is limited to what could be achieved using the keyboard.
Not sure if this is a worthwhile idea or not, but it seems to work reasonably well. Could probably use some refinement.

Heretic/Hexen: Capture mouselook activity when recording a demo

---

src/heretic/d_main.c
src/heretic/mn_menu.c

Here's my attempt at the status bar level stats for Heretic. 
One difference from the Doom implementation is that in fullscreen mode I move the stats widget back to the corner, same as when the automap is active. I found it to look a little out of place otherwise.

Heretic: Add status bar stats widget

---

src/doom/p_saveg.c

reset mobj_t fields used for interpolation when loading savegame

---

src/doom/am_map.c
src/heretic/am_map.c
src/hexen/am_map.c

Panning and scrolling now function properly when running uncapped. I had to alter the interpolation math in order to keep the scrolling and panning from going out of sync due to accumulation of round-off error.
I've only updated Heretic so far. @JNechaevsky and @fabiangreffrath if you agree with my approach I will proceed to update Hexen and Doom next.
(Also I noticed that keyboard zooming exhibited a hitch after using the mouse. I went ahead and fixed that here as well.)

Automap panning and scrolling interpolation improvements

---

src/doom/am_map.c
src/doom/am_map.h
src/doom/d_main.c
src/doom/g_game.c
src/doom/hu_stuff.c
src/doom/p_inter.c
src/doom/s_sound.c
src/doom/st_stuff.c
src/doom/st_stuff.h

No desyncs! Just a fixes for demos/games with more than one player. So far, what I have found:
Testing map and demo with four players: [yardz.zip](https://github.com/chocolate-doom/chocolate-doom/files/9331105/yardz.zip)
_Demo is originally "SPB_MSC1.LMP", but renamed for simpler loading. It's a deathmatch of St.Petersburg vs. Moscow, dated 1996-05-28. Good old times..._

Doom: various multiplayer fixes

---

src/doom/r_bmaps.c

Same PR to https://github.com/fabiangreffrath/woof/pull/742. Using tabs, not spaces.

Apply `bluegreenbrownred` brightmap to `COMPUTE1` texture

---

src/doom/hu_stuff.c

Just as I have promised. This should allow chat line properly appear. Comparative screenshots: [before](https://user-images.githubusercontent.com/21193394/189541073-acc34f58-9140-44c5-899c-0f62449defa5.png) and [after](https://user-images.githubusercontent.com/21193394/189541093-1e34adfd-781f-4884-bf8b-639ac586e209.png).
However, I'm starting to forget how original HUD system is working after rewriting it on ID, so... Have I missed something? Any thoughts or corrections? And maybe we don't need it while demo playing since no chat string are recording in demos?

Doom: shift widgets one line down so chat typing line may appear

---

src/heretic/mn_menu.c
src/hexen/mn_menu.c

Bring the Heretic/Hexen Crispness menu closer to parity with the Doom menu.
- Left and right keys now cycle through options with the correct direction
- Use page up/down to change menus in Heretic
- Colorize options in the same manner as Doom; no coloring corresponds to vanilla behavior
- Minor refactoring to better match the Doom code
Any Doom Crispness behavior that I missed?

Raven: Crispness menu quality-of-life improvements

---

src/setup/sound.c

Now Crispy Doom can play MP3/OGG/FLAC music with OPL and GUS backend. Not sure if "Native MIDI" is appropriate.

Restore old music backend name "Native MIDI"

---

src/i_sdlmusic.c
src/i_sound.c

Noticed that after #975 `I_SDL_InitMusic` was being called twice.

Don't initialize SDL music module twice

---

src/crispy.h
src/doom/m_crispy.c
src/doom/m_crispy.h
src/doom/m_menu.c
src/doom/m_menu.h
src/heretic/mn_menu.c
src/hexen/mn_menu.c
src/i_video.c

Here's a first go at adding this to Doom. To fit the new item in, I opted to move everything up. Objections to this approach are welcome. :smiley:
Before:
After:
I think it is prudent to disable the option when Uncapped Framerate is off, so I have done so here.
Once everyone's happy with the base implementation I'll port it over to the Raven games and un-draft the PR.
Fixes #979.

Add FPS Limit to Crispness menus

---

src/doom/m_menu.c
src/heretic/mn_menu.c
src/hexen/mn_menu.c

For some reason MSVC doesn't like `const` variables for array size, see [C2057](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2057?view=msvc-170) (C section)

Fix MSVC compiler error (C2057)

---

src/heretic/mn_menu.c
src/hexen/mn_menu.c

Not sure if this is an improvement or not, but I wanted to get it out there for comment.
Heretic before/after:
Hexen before/after:

Raven: Make Crispness menu appearance more like Doom's

---

src/i_musicpack.c

Related to fabiangreffrath#738.
Apparently music pack CFG files are deprecated (chocolate-doom#1576), so I added hardcoded hashes for the MIDI tracks to the `known_filenames[]` array in `i_musicpack.c`. This allows music packs for the MIDI version of the Sigil's soundtrack ([such as these](https://www.doomworld.com/forum/topic/121305-sigil-roland-sc-55-music-pack/)) to be installed without generating a music pack CFG file. I figure this makes sense to include in the hardcoded list, since Crispy already autodetects Sigil for use as a fifth episode when using Ultimate Doom's IWAD.
Vanilla Chocolate Doom doesn't support Sigil, so I am PRing this here, rather than upstream where the list comes from.

Add known hashes for Sigil music tracks

---

src/doom/p_pspr.c

This is easy to test with the chainsaw. The "choppy" vanilla behavior is preserved when not using an uncapped framerate. Example:
```
crispy_bobfactor              0
crispy_centerweapon           0
crispy_fpslimit               0
crispy_uncapped               0 (left side of video)
crispy_uncapped               1 (right side of video)
```
https://user-images.githubusercontent.com/56656010/216466247-42000322-173e-4c71-8d15-dc7ffee84364.mp4
[Doomworld post with more details](https://www.doomworld.com/forum/topic/121183-which-of-these-chainsaw-animations-is-the-correct-one/?tab=comments#comment-2292505)

doom: Always interpolate idle weapon bob with uncapped FPS

---

src/heretic/g_game.c
src/hexen/g_game.c

* Fixes "Look forward" button not working properly while recording a demo. `TOCENTER` command uses -8 value of look variable, so in `demorecording` mode it was always overwritten with -2 by the `look < -2` check.
* Due to `cmd->lookdir /= MLOOKUNIT` there was a dead zone in vertical mouse movement around 0 value. This dead zone can be eliminated by using `ceilf()` and `floorf()` resulting in identical behavior and feeling of vertical and horizontal mouse look.

Heretic & Hexen: Fixes and enhancements for vertical mouse look

---

src/doom/m_crispy.c

Applied `ChangeSettingEnum()` to `M_CrispyToggleColoredblood` so that the settings can be changed in both directions.

Colored blood setting to change in both directions

---

src/strife/m_menu.c

In order to support widescreen graphics mods, `patchclip_callback` checks were bypassed in https://github.com/fabiangreffrath/crispy-doom/commit/96dbc26339ad9416e9386c17b7b42446d23d3417. I went through every `V_Draw*()` function call where this applies and the only regression is the Sigil cursor (this is the skull in Doom) showing in the help screen when it shouldn't. This PR hides the cursor to match vanilla behavior. Normally, the cursor is positioned on the help screens in a way that would cause Strife to ignore the draw request since it's partially offscreen. Now the draw calls are skipped in `M_Drawer()`.

strife: Don't show cursor on help screens

---

src/strife/hu_stuff.c
src/strife/p_inter.c
src/strife/p_pspr.c
src/strife/r_things.c

1. Revert adjustments to targeter positioning from https://github.com/fabiangreffrath/crispy-doom/commit/066ae50952e3ca699ebddd71a6d3327219f5d02a. I don't want to interfere with modders who change the targeter sprites and their offsets.
2. Don't show Crispy crosshair when targeter is active.
3. Don't interpolate targeter sprites.

strife: Crosshair and targeter adjustments

---

src/doom/r_things.c
src/strife/r_things.c

Moved the free look calculation to after interpolation. This is also the approach used by Woof. Heretic and Hexen are similar as well. Reported by OpenRift.
https://user-images.githubusercontent.com/56656010/220836366-00636894-b824-4ab2-8132-ab2e4d585ff2.mp4

doom/strife: Fix free look judder

---

src/setup/mainmenu.c

Accessibility settings aren't implemented in non-Doom games so it would be unfortunate if someone expected these settings to function when they currently do not.

Hide accessibility menu in non-Doom games

---

src/heretic/d_main.c

There is ongoing Heretic project that will probably use the HHE file. Users will be required to use the command line with the `-deh` and `-hhever` options. Much more convenient if there is support for built-in PWAD HHE files.
This can be a very obscure feature only used in one PWAD. To my knowledge, no other Heretic port supports HHE.
We are currently assuming Heretic version 1.0, but maybe set 1.3 as the default for HEREHACK?

heretic: Introduce a HEHACKED lump for embedded HHE files

---

src/doom/g_game.c
src/doom/hu_lib.c
src/doom/hu_stuff.c

This pull request fixes some HUD issues:
1) static crosshair not drawn in case of automap overlay;
2) kills string not moved down when multiplayer chat line is active;
3) chat string getting colored after toggling always run.

Minor HUD fixes

---

src/i_video.c

This will allow `-timedemo` to run with full available power. Please correct me if I'm wrong.

Don't calculate `fractionaltic` and don't cap FPS in `-timedemo`

---

README.md

We must use full links as we distribute README.md in zip archives.
Updated wiki: https://github.com/fabiangreffrath/crispy-doom/wiki Should we delete old pages?
cc @kiwphi

fix README.md wiki links

---

src/doom/d_main.c
src/doom/d_main.h
src/doom/g_game.c
src/heretic/g_game.c
src/memio.c
src/w_wad.c
src/w_wad.h

Petition to developers: [[doomworld]](https://www.doomworld.com/forum/topic/134189-petition-to-all-developers-of-demo-compatible-ports-about-lmp-footer/)
There is potential issue with sideloading, e.g. "NERVE.WAD" appears in demo footer wad list but not used.

Make demo footer compatible with PrBoom+/DSDA-Doom demo autoplay

---

src/doom/hu_stuff.c
src/doom/st_stuff.c
src/doom/st_stuff.h

Another minor fix that appears logical to me

Status bar level stats alignment matching HUD width

---

src/doom/hu_stuff.c

Fixed Kills line position when switching level stats display from Status bar to a different option

---

src/doom/p_floor.c

Demo: [door.zip](https://github.com/fabiangreffrath/crispy-doom/files/11730464/door.zip)
Thanks to @JNechaevsky for bug report and demo.

Fix door interpolation in Doom 2 MAP19

---

src/doom/g_game.c

Should we print complevel for `exe_chex` and `exe_hacx`?

fix complevel 3 in demo footer

---

src/doom/r_bmaps.c

Details and testing map: https://github.com/JNechaevsky/international-doom/commit/92e4e71e34a569fc38983c08ebb0401fd9e34cf1.

Use `GREENONLY1` brightmap for Armor Bonus

---

src/doom/r_bmaps.c

Same way we have done already in [Woof](https://github.com/fabiangreffrath/woof/pull/1179) in [Inter-Doom](https://github.com/JNechaevsky/international-doom/pull/14).

Improve BFG and SW2STONE brightmaps

---

src/doom/p_map.c
src/doom/p_user.c

While cleaning up my amateur mistakes to prepare the new release of So Doom I noticed that Crispy code looks to contain flaws that may be seldom triggered.
The physical gameplay tweaks that affect demo sync and netplay should be set up as `crispy->criticalfield` in 4 files only:
`compatibility.c`, `d_main.c`, `m_crispy.c` and `m_menu.c`.
In all other files the `critical` structure pointer should be used instead of `crispy`, `critical` points to `crispy_s` struct in singleplayer (non-demo, non-netgame) and to the all-zeros-initialized `critical_s` otherwise.
I cleaned out what looks to me like the wrong use of `crispy->` instead of `critical->`.

Always use critical struct for freeaim and jump

---

src/doom/p_mobj.h

For Heretic, Hexen and Strife the meaningful comments are present.

Clarified MF_TRANSSHIFT purpose comment in Doom

---

src/v_trans.c

Same problem, described by @liPillON happens in Crispy Doom as well, though it's less noticeable because of `CR_GREEN` formula is slightly different from Woof. Anyways, result with D2TWID.wad loaded:
Before:
After:
Original commit from Woof: https://github.com/fabiangreffrath/woof/commit/62cd1e29a2159f881c236c26edc9bf1da70757af

Move green color translation formula one step away from cyan

---

src/doom/st_stuff.c

Currently, if the player enables god mode through the IDDQD cheat, dies, and then enters the cheat again to respawn, they'll respawn in a "zombie" state (which I assume is not intentional), similar to [this](https://youtu.be/0XKIB8mkYMs?si=to9z-rFo5-uFGMcg&t=154), because health is not reset from 0. This is unlikely to happen because the player shouldn't die in god mode, but it's possible in some cases, like telefragging.
This PR forces the player's health to that of god mode when respawning through IDDQD, regardless of whether god mode is being enabled or disabled, which doesn't change anything for the former case, and fixes respawning for the latter.

IDDQD: fix reviving if god mode was already enabled

---

src/strife/d_main.c
src/strife/r_things.c

The command line parameter `-flip` is a partially broken and undocumented [vanilla Strife feature](https://doomwiki.org/wiki/Parameter#-flip). This is now fixed for Crispy Strife. There is a similar feature in Crispy Doom, `-flipweapons`, so this has been added as an alias. Requested by @eggman07 on the Chocolate Discord.

strife: Add flipped weapon sprites

---

src/doom/g_game.c
src/doom/g_game.h
src/doom/m_menu.c
src/doom/p_mobj.c
src/doom/s_sound.c
src/i_video.c

Initial PR: https://github.com/JNechaevsky/international-doom/pull/27
Remaining TODO: no luck with proper music changing in Crispy code. Needs some investigation why, and probably will need some help here.

Implement reload / go to next level while demo playing

---

src/doom/m_menu.c

key_menu_forward should behave like key_menu_right for enum items in the Crispness menu.
Trying to correct a dumb oversight from the last time I touched this code. :man_facepalming: Better late than never!

doom: Fix key_menu_forward in Crispness menu

---

src/doom/r_data.c
src/heretic/am_map.c
src/heretic/d_main.c
src/heretic/f_finale.c
src/heretic/in_lude.c
src/heretic/mn_menu.c
src/heretic/p_user.c
src/heretic/r_data.c
src/heretic/r_draw.c
src/heretic/r_local.h
src/heretic/r_main.c
src/heretic/r_plane.c
src/heretic/r_things.c
src/heretic/sb_bar.c
src/i_video.c
src/i_video.h
src/v_trans.h
src/v_video.c
src/v_video.h

Pretty much same to Doom, except much more strict with translucency effects - we **must** keep original look & feel as much as possible, so there is no additive blending.
I wasn't able to resolve two small remaining problems:
1. [Chain shading](https://github.com/fabiangreffrath/crispy-doom/blob/truecolor_heretic/src/heretic/sb_bar.c#L435). No idea what to do, simple replacement of `byte` to `pixel_t` doesn't work. Something must be wrong with either `dest =` declaring, or inside `while` loop.
2. [Automap background drawing/parallaxing](https://github.com/fabiangreffrath/crispy-doom/blob/truecolor_heretic/src/heretic/am_map.c#L1121-L1128). Since `maplump` is a 320x158 raw screen, we can't use `memcpy` here. In theory, we can draw it same way as common 64x64 flat tiles, but how to achieve …

Heretic: add true color support

---

src/heretic/r_draw.c
src/heretic/r_plane.c
src/heretic/r_things.c

This is a small collection of small visual improvements. Nothing critical, until you'll see them or know about them. 🙃 To clarify:
**1.** Weapons drawn 1 pixel too high when player is idle. Fixes notable moving weapon for one pixel down even while small movement/momentum. Formula `FRACUNIT / 4` comes directly from Doom and it's working fine.
**2.** Fix 1px gap between translucent PSPrite and STbar. Fixes missing one pixel line above status bar for translucent columns.
<details>
</details>
**3.** Allow translucent weapons to be affected by invul colormap. Just a small vanilla oversight, fix does not affect sky of course.
<details>
</details>

Heretic: small visual improvements

---

src/doom/st_stuff.c
src/heretic/p_inter.c
src/heretic/sb_bar.c
src/hexen/p_enemy.c
src/hexen/p_inter.c
src/hexen/sb_bar.c
src/strife/st_stuff.c

Same as described and done in https://github.com/fabiangreffrath/woof/pull/1316. Few remarks:
- Heretic have `void SB_PaletteFlash(void)` in p_local.h. Kept it there for smaller diff, so no static declaration.
- Hexen handles `F11` just a very little bit different, so call for `SB_PaletteFlash(true)` is still needed in mn_menu.c
- Maybe add some comments?

Invoke ST_doPaletteStuff every game tic, not every frame

---

src/heretic/r_bsp.c
src/heretic/r_segs.c

This glitch with animated floor attracted my attention (hey, isn't the gamma is beautiful now?):
<details>
https://github.com/fabiangreffrath/crispy-doom/assets/21193394/cefaf847-3e16-4cf2-9277-b2f0afd9b64c
</details>
On a first look it might appear as huge slime trail or broken map nodes, but no, it is much simpler. When sector lowers to nearest floor, following happens in this scene:
- Both sectors have same floor height.
- Both sectors have same ceiling height.
- Both sectors have same lighting level.
- And only sector specials are different: upper is Scroll East, lower is Scroll South (effect is invisible).
This all makes clear explanation: engine thinking that both visplanes can be merged into one for rendering. In fact, it's a small oversight in original Heretic code, and I missed …

Heretic: check for sector->special for proper visplanes clipping

---

src/doom/am_map.c
src/strife/am_map.c

Fixes this case in widescreen mode:
<details>
https://github.com/fabiangreffrath/crispy-doom/assets/21193394/aeddba76-b5f5-46c6-a1e5-33cc717bd3a4
</details>
Hovewer! There is a small problem with Doom, caused by `flipscreenwidth`. This is won't happent if just `CXMTOF(pt.x)` will be used. Note how `1` is blinking and appearing when it shouldn't. It was happening even before my fix.
<details>
https://github.com/fabiangreffrath/crispy-doom/assets/21193394/94a81d34-e00f-4fce-9519-4f2cb6dec85d
</details>
Not sure how to fix this blinking, no ideas yet... 🤔

Fix automap marks dissapering near left side of the screen

---

src/doom/r_draw.c
src/heretic/r_draw.c
src/hexen/r_draw.c

Same idea and aproach as in https://github.com/fabiangreffrath/woof/pull/1340. No new functions, just extended current ones to draw brightmapped pixels. Few remarks:
- For Doom we _deffinitly_ needed, and it's easy to test with a [testing map](https://github.com/fabiangreffrath/woof/files/13697596/tl_bmap.zip) from Woof's PR. There is not translucent walls in original Specifics, it's a Boom-ism. Small expection was made long time ago for scrolling texture right, AFAIR, just as small possible nicification for NOVA.wad.
- For Heretic we _probably_ need it. Testing translucent columns was easy, just set `MF_SHADOW` flag to Phoenix Rod, but testing translucent+translated columns - no idea how. Neigher I am able to run HeHacked, this is what always happening with 1.3 version for DOS …

Apply brightmaps to translucent and translated columns

---

src/heretic/r_draw.c

This adds missing change to R_DrawTranslatedTLColumn()` in true color render.

Heretic: add missing change for R_DrawTranslatedTLColumn

---

src/i_sound.c

I noticed that the Sigil and Sigil II MP3 soundtracks would always start off at max volume when sideloading. This fixes that.

Always set SDL music volume

---

src/crispy.c

Quite obvious, in C array indices begin with 0, so 10th element has index 9

The zero gamma index in array is 9, not 10

---

src/heretic/r_bmaps.c

Not very noticeable in vanilla Heretic as fighting area is pretty bright, but the missing brightmap is quite noticeable in Curse of D'Sparil. Basically, this, `TELE` (left) is for destination `TELEFADE` (right) is for source D'Sparil state:
Have to admit, it's pretty cool effect technically, as mobj is not immediately moving from one coord to another, but splitted to two mobjs.
_Original issue: https://github.com/JNechaevsky/international-doom/commit/246fd169ed36bb5a96439c0684c2ebf432a86a0b_

Heretic: apply brightmaps to D'Sparil teleporting frames

---

src/heretic/CMakeLists.txt
src/heretic/Makefile.am
src/heretic/doomdef.h
src/heretic/p_blockmap.c
src/heretic/p_setup.c

As always, few remarks:
* I believe old P_GroupLines code is from Doom 1.2, as according [DoomWiki](https://doomwiki.org/wiki/Heretic), Heretic itself is based on Doom 1.2.
* Comment about "...from Chocolate Doom" is deliberately, as [released source code](https://github.com/id-Software/DOOM/blob/master/linuxdoom-1.10/p_setup.c#L499) Doom 1.10 have minimal difference in P_GroupLines (notably, Z_Malloc).
* I have slightly changed final printf in P_CreateBlockMap and excluded printf below [this line](https://github.com/fabiangreffrath/crispy-doom/compare/master...fabiangreffrath:crispy-doom:htic_psetup?expand=1#diff-d721c5a378dbfc38a4457bc895b9ae688c31da823c0009d25fe806b79129ccddR565) to better match of Crispy Heretic printfs since there is no "better logging" like in Crispy Doom. 
* _[That …

Heretic: update P_GroupLines and (re-)create BLOCKMAP if necessary

---

src/doom/p_map.c
src/heretic/m_random.c
src/heretic/m_random.h
src/heretic/p_local.h
src/heretic/p_map.c
src/heretic/p_mobj.c

Barely I need to make any explanations for your code. Just a few remarks, as always:
* This is a two-in-one fix, for both hitscan puffs wasn't able to hit floor/ceiling and projectiles were disappearing on some two sided lines.
* There are no `acv` action pointers in Heretic, that's the only difference in `P_LatestSafeState` function.
* You may notice a small knockback when using Phoenix Rod (local rocket launcer). This is not because of splash damage (health isn't touched), this is [by design](https://github.com/fabiangreffrath/crispy-doom/blob/master/src/heretic/p_pspr.c#L1623-L1624) in original game mechanics.
* Testing map: We won't be visiting _that MAP15_ today. Instead, we will visit E1M8 of Doom 1, recreated in Heretic as E1M1. 😮 Why? It have all necessary for testing, that's the …

Heretic: fix hitscan/missile puffs disappearing in certain areas

---

src/heretic/mn_menu.c
src/hexen/mn_menu.c

As suggested in https://github.com/fabiangreffrath/crispy-doom/issues/1137#issuecomment-1899920487. Few remarks:
- Not sure if comment fits well. Technically it's described pretty clear in [original code](https://github.com/fabiangreffrath/crispy-doom/blob/master/src/heretic/g_game.c#L100).
- There are no `false` in Hexen, as `SCSaveGame` is a `void` function type, not a `boolean`.
Fixes https://github.com/fabiangreffrath/crispy-doom/issues/1137.

Heretic and Hexen: check if saving is allowed

---

src/heretic/am_map.c

This PR carefully reverts `COLORMAP`-based automap line smoothing to original tablified approach, but keeps true color support. I used WinMerge to bring changes back from released version of Crispy Heretic 6.0. 
Unfortunately, this approach is less mod compatible, as line smoothing now relies to `PLAYPAL` indexes again, but:
* Not sure are the any mods for Heretic with heavily modified `PLAYPAL`.
* This bring back original look&feel of automap, and line smoothing feels much for decent. Fading is also back.
* It finally solves that painful _"starts from dark, ends with darker"_ problem, though it's a bit personal nitpick.
Please note, there are few black lines - it's a vanilla behavior. Such coloring happens only while using `RAVMAP` (show full map cheat).
As a mater of fact, only this …

Heretic: back to tablified automap colors antialiasing

---

src/doom/d_pwad.c
src/doom/wi_stuff.c
src/w_main.c
src/w_main.h

* Lumps in autoloaded wads pulled in by sideloading are now subject to the same renaming as the original sideloaded wad. (Fixes #1094)
* Apply TITLEPIC and INTERPIC renaming to Master Levels autoloads when sideloading. Also, grant the Master Levels its own intermission picture.
* Autoload from the MASTERLEVELS.WAD directory when using the loose Master Levels files.

Minor sideloading improvements

---

src/heretic/r_plane.c

Crispy already has x and y offsets on flats for interpolated scrolling. Using these for drawing all scrolling flats means any flat can scroll, and (optionally) in any direction, without visual errors.
Unsure about line lengths and formatting, also whether I should move visual and audible crispness options to a new page as the first page is crowded right now.
Example wad, also see Heretic E5M2 or any other level with water.
[htic_scroll.zip](https://github.com/fabiangreffrath/crispy-doom/files/14002774/htic_scroll.zip)

Heretic: improve flat scrolling animations

---

src/heretic/g_game.c
src/heretic/mn_menu.c
src/hexen/g_game.c
src/hexen/mn_menu.c

- Enable `demospeed` key, and disable opening the menu when a non-menu key is pressed
- Check `usergame` when not in a demo properly
This could also be applied to Chocolate Doom but I don't think it's necessary since `-demoextend` is not the default.

Heretic & Hexen: demo playback fixes

---

src/doom/r_data.c
src/heretic/r_data.c
src/hexen/am_map.c
src/hexen/f_finale.c
src/hexen/h2_main.c
src/hexen/in_lude.c
src/hexen/mn_menu.c
src/hexen/p_pspr.c
src/hexen/p_setup.c
src/hexen/p_user.c
src/hexen/r_data.c
src/hexen/r_draw.c
src/hexen/r_local.h
src/hexen/r_plane.c
src/hexen/r_things.c
src/hexen/sb_bar.c
src/i_video.c
src/strife/r_data.c
src/v_trans.h
src/v_video.c

Almost a carbon copy of Doom and Heretic code with few exceptions. At the moment of writing this PR, all rendering initials and nominals should be formed, and despite of massive changes this is an easy part. Hard part is:
* Extra color panes to support 13-27 palette indexes. And what about formulas?
* Foggy maps should use pregenerated colormap table + there is something unclear with brightest levels, see my comment at p_setup.c.
* Fade in / fade out effects for finale screen. We can't operate with `PLAYPAL` values, but we can fade screen with `I_BlendDark` in f_finale.c.
* I'm sure there can potentially be couple of underwater mines in ACS scripts.

Hexen: add true color support 

---

src/heretic/r_data.c
src/hexen/r_data.c

This is largely Lee Killough's original fix taken from MBF. There are some extra improvements that Fabian added to Doom that are not present here. In particular this implementation does not composite single patch textures, because doing so breaks the Heretic and Hexen skies.
Fixes #1146.

raven: Fix medusa effect

---

src/hexen/p_setup.c
src/hexen/r_bsp.c
src/hexen/r_local.h
src/hexen/r_main.c

This will fix possible overflows on walls rendering. Probably it was brought by fixing long wall wobbling, but recently introduced "pseudo-vertexes" (or "render-vertexes" as they called now) by @mikeday0 make this fix very easy.
This glitch is happening in released version 6.0, but appears rarely in general. Faster way to see it is to `VISIT09` (first part of video), and it looks likes this: https://youtu.be/aFf-EdLE9MM

Hexen: fix possible overflows on walls rendering

---

src/heretic/r_bmaps.c

The stem of the torch uses a colour included in the 'flame' brightmap on a few pixels, and it looks funny in the dark. The head of the torch uses this colour too but it still doesn't look too bad when it's excluded from the brightmap.
See https://github.com/JNechaevsky/international-doom/pull/69 for images.

Heretic: custom brightmap for serpent torch

---

src/hexen/r_main.c

Unlike Heretic, there is no invulnerability colormap in Hexen. However, this redundant `sizeof()` multiplier slightly breaks fixed colormap indexes while using Torch arrtifact: index may go too low, making game map notably darker than it should. This was fixed in Heretic [already](https://github.com/fabiangreffrath/crispy-doom/pull/1111/commits/dad0d47ed01e38218d86196b70f613ec97825ab4), but missed while true color implementation.
Kind thanks to @kitchen-ace for [pointing out](https://github.com/JNechaevsky/international-doom/issues/73).

Hexen: remove redundant sizeof multipler for fixed colormaps handling

---

src/hexen/p_map.c

Lexi's comment explains itself, this fixes rendering glitch while silent teleportation effect. Unfortunately, Raven Software's implementation is not even close to be as smooth as it was done in Boom engine, matters no is it capped or uncapped frame rate. 
On first looks it seems that `deltaviewheight` or bob factor is not carried properly to teleport destination, and it was accounted in [Boom implementation](https://github.com/fabiangreffrath/woof/blob/master/src/p_telept.c#L166-L181), but it doesn't seems to be safe to copy-over, extra touching of `P_CalcHeight` _may_ or _will_ cause demo desync. Probably worth to leave leave "as is" for good...
This should fix https://github.com/fabiangreffrath/crispy-doom/issues/1157, kind thanks to @kitchen-ace for pointing out.

Hexen: don't interpolate mobjs that pass through teleporters

---

src/i_sdlsound.c
src/setup/sound.c

The default for `use_libsamplerate` is 1 which in turn selects linear interpolation for the resampling process. Unlike windowed sinc, linear interpolation cannot introduce any new clipping into the waveform. Therefore we should use a default of 1.0 for `libsamplerate_scale`. This will give the sound effects a bit of a volume boost compared to the previous default of 0.65, and Crispy should now have better volume matching with other ports.
Closes #1162.

Get full output from libsamplerate by default

---

src/hexen/p_setup.c

[This line](https://github.com/fabiangreffrath/crispy-doom/blob/master/src/hexen/p_setup.c#L221) is now redundant, as such rendering-only lines now calculated enterely in `P_SegLengths`, i.e. [here](https://github.com/fabiangreffrath/crispy-doom/blob/master/src/hexen/p_setup.c#L268).

Hexen: remove redundant r_angle initialization

---

src/heretic/p_mobj.c

To fix possible demo desyncs. Kind thanks @kitchen-ace for pointing out! Fixes https://github.com/fabiangreffrath/crispy-doom/issues/1169

Heretic: use safe function for puff spawning

---

src/doom/m_menu.c

Heretic, Hexen and Strife already had the 'Widescreen" word removed because there is an option for original aspect ratio.
Doom should too :)

Aspect ratio wording for Doom

---

src/heretic/mn_menu.c
src/hexen/mn_menu.c

Fixes minor regression in #1151
Thanks @mikeday0
I kept it simple and just changed to check against `!singledemo`. Map and fast-forward still bring up the menu in internal demos as a result, but I doubt anyone will care.

Heretic & Hexen: any key opens the menu when not in a demo

---

src/hexen/am_map.c

This was the case when palette indexes were doing right thing, but actual colors are not. Such approach with `1...8` is working fine in normal automap mode because colors are "fading" to parch background color, but situation is a bit different in overlay mode.
This approach slightly reduces amount of smoothing colors, yet preserves reasonable smoothing, making lines slightly less... _broken_ (not sure what's word is more correct here). And the result is: [before](https://github.com/fabiangreffrath/crispy-doom/assets/21193394/6c7ae7ce-ea8a-4ee5-a855-4e812dcb4eb5) and [after](https://github.com/fabiangreffrath/crispy-doom/assets/21193394/d3b1e68f-0b7c-40dd-8f2f-3df9480bdc52). Please note that fading to dark near the screen borders is now reduced, but I believe it's a small price, at least …

Hexen: improve line drawing in automap overlay mode

---

src/heretic/mn_menu.c
src/hexen/mn_menu.c

This fixes small issue in Raven menu code when deleting a save game resets cursor position to last actual save (or first slot if no save was made). Small demonstration:
https://github.com/fabiangreffrath/crispy-doom/assets/21193394/bc6cb9f9-6fa3-4bd8-a78c-b6b99c91088a
I'm deleting `5`, `2` and `3` slots (let's count from one, not from zero 🙂), and cursor is jumping to slot `1` after deleting. It behaves same way in Heretic, as menu system is almost identical.

Heretic & Hexen: keep cursor position after deleting a save game

---

src/heretic/mn_menu.c
src/hexen/mn_menu.c

This is a tiny correction to fix tiny oversight in Raven menu system. How to see this oversight in action:
- Go to the standard Options menu, where three menu items with "M" names are placed (Messages, Mouse sensitivity and More).
- Press `M` on a keyboard. Cursor will move to Messages item.
- Press `M` again. Nothing happens, cursor will stay on same menu item.
- Same problem applies to Crispness menu, and this fix will handle it.
In Doom, however, in Options menu cursor will move to the next menu item with same first letter (Messages/Mouse sensitivity or Screen size/Sound volume). My first though such oversight was a leftover from Doom 1.2, but nope, even Doom 0.99 shareware supports multiple jumps.
The approach itself is basically a carbon copy of implementation [from …

Raven: allow multiple jumps over menu items with same first letters

---

src/heretic/p_doors.c

Very rare case and pretty straight-forward fix, but as always, few remarks:
* The fix itself is a carbon copy from [Crispy Doom](https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/p_doors.c#L426-L431), except using `printf`, not `fprintf` (I belive printing into a file no longer needed since SDL2 version).
* Testing map, DR door on one sided line is in front of the player view: [dr-1side.zip](https://github.com/fabiangreffrath/crispy-doom/files/14812674/dr-1side.zip)
Fixes https://github.com/fabiangreffrath/crispy-doom/issues/1188, thanks @Catoptromancy for pointing out.

Heretic: do not crash if the wrong side of the door is pushed

---

src/doom/r_things.c
src/i_video.c
src/strife/am_map.c
src/strife/d_main.c
src/strife/f_wipe.c
src/strife/f_wipe.h
src/strife/m_menu.c
src/strife/r_data.c
src/strife/r_defs.h
src/strife/r_draw.c
src/strife/r_main.c
src/strife/r_main.h
src/strife/r_state.h
src/strife/r_things.c
src/strife/st_stuff.c
src/v_trans.h
src/v_video.c
src/v_video.h

This is the final chapter of Crispy true color story, what else can be said? 🙂 Just a few remarks and TODOs:
- ~~TODO: Screen wiping disabled. It is not possible to use `XLATAB` neither for crossfading, nor for any kind of translucency. Wiping effect will require entirely different approach, probably via some SDL functions, like making a copy of existing texture and blending it with variable opacity level, depending on game tic or something. No idea how to proceed at the moment.~~
- ~~TODOs : Graphical startup with RAW patches working, but not sure it's an optimal way, since `pal_color[]` must be filled before graphical startup, and then filled again after generating colormaps.~~
- ~~Brightmaps working. Strife is using `COLORMAP` for such trick, it was easy it replicate it by locking …

Strife: add true color support

---

src/i_video.c

This fixes nasty typo I made while overlay blending functions simplification. Sorry for inconvenience!

Fix typo in I_BlendOverTranmap

---

src/doom/m_menu.c
src/heretic/g_game.c
src/heretic/mn_menu.c
src/hexen/g_game.c
src/hexen/mn_menu.c
src/strife/m_menu.c

Small collection of various menu control improvements.
Following actions can be confirmed by `Enter` key:
- Nightmare skill verifying (Doom only)
- End game
- Quit
- Suicide confirmation (Hexen only) is possible but not included - probably it's too dangerous, just like savegames deleting - user have to confirm such actions strictly by `Y` key.
Heretic and Hexen:
- Menus can be scrolled via mouse wheel.
- Small addition - allow to quit by pressing `F10` in any game states, so user won't need to open game menu and select "Quit Game", if the game wasn't started.
Extra:
- Slightly reduced delay between `LMB`/`RMB` clicks, so user now can go through actions like "New Game > Episode > Skill level" by faster clicking.

Various menu control improvements

---

src/doom/m_menu.c
src/heretic/mn_menu.c
src/hexen/mn_menu.c
src/i_main.c
src/strife/m_menu.c

Show date and time of savegame in Save/Load menu

---

src/heretic/am_map.c
src/heretic/mn_menu.c
src/hexen/mn_menu.c

This should fix possible crashes in cases like:
* Using lowercased designation (`am/pm` instead of `AM/PM`) in savegame time. This was fixed by not drawing lowercase characters.
* Lowecased text can be used for both big and small fonts, probably good for compatibility with mods.
* Unknown characters (not existing in font graphics) are still replaced with spaces.

Heretic and Hexen: check for valid, existing characters in font drawing functions

---

src/strife/m_menu.c

My bad, brought by Save/Load menu centering/rearrangement and always using `crispy-strife.exe -loadgame 0` for faster startup.
Before and after:
<details>
</details>

Strife: fix "Name Your Character" menu

---

src/strife/d_main.c
src/strife/f_wipe.c

That's it, as simple as it gets. If feels slightly longer than original effect, presumably by just a few tics (yeah, inner timer is a thing), but looks absolutely fine and smooth.
TODOs:
* Not sure why `wipe_scr` wants to be `I_VideoBuffer`. Should it be `Z_Malloc`'ed like in paletted render, then effect will be notably faster in speed and less epic. Same applies to drawing solid background while crossfading effect, but it shouldn't be that CPU-expensive, as the effect itself is `gametic` based.
* ~~Memory leak is still happening. That's odd, since all `pixel_t` variables are seems to be freed.~~ Fixed!

Strife: improve TrueColor crossfading effect

---

src/doom/r_main.c
src/strife/r_main.c

This fixes memory leak (over-consumption) by toggling detail mode or changing screen size. Few remarks:
* Probably not worth a comment, as this is our own code not a Chocolate one.
* Nothing for Heretic & Hexen since there is not smooth diminished lighting. It's a must have for TrueColor to be honest, but I'm not sure how to fit it in Crispness menu.
* This approach is pretty much same to [Woof](https://github.com/fabiangreffrath/woof/blob/master/src/r_main.c#L470-L471) one.
Small note - it was barely possible to notice a leak while non-TrueColor build, obliviously because of smaller `lighttable_t` size. However, while experimenting with colored lighting and having 28 [extra colormaps](https://github.com/JNechaevsky/yaguar-doom/blob/main/src/doom/r_collit.c#L472-L502) (both `scalelight` …

Fix scalelight[] memory leak

---

src/doom/g_game.c
src/heretic/g_game.c

Fixes the case described in PR for Woof: https://github.com/fabiangreffrath/woof/pull/1799
Only for Doom and Heretic at the moment, since "Reload Level / Go to Next Level" keys is only available for these two games. Not sure if Hexen and Strife needs this until level keys will be implemented.

Doom & Heretic: suppress pause when a new game is started

---

src/doom/r_things.c

Use `FRACUNIT/(2<<crispy->hires)` instead of `FRACUNIT/constant`.
Sorry @JNechaevsky, flexible solutions are usually better.

Resolution-tuned weapon sprite 1 pixel height adjustment for compatibility with bit-shifting hires forks

---

src/hexen/r_draw.c

Same as it was done for Heretic, this will fix missing one pixel line at top and bottom of screen for transparent drawing functions. Like on a screenshot, showed in [this](https://github.com/fabiangreffrath/crispy-doom/pull/1171#issuecomment-2266497116) post.

Hexen: show transparent lines at top and bottom of screen

---

src/doom/p_setup.c

Thanks @kitchen-ace for [suggestion](https://www.doomworld.com/forum/topic/112333-this-is-woof-1450-apr-30-2024/?do=findComment&comment=2827653) to have a fix, and tanks @rfomin for [suggesting](https://www.doomworld.com/forum/topic/112333-this-is-woof-1450-apr-30-2024/?do=findComment&comment=2827758) a fix from PrBoom+.
Dear reader, please note: this fix is not hot-swappable and will require savegame or level reloading.

Doom: fix sector's sound origin for large levels

---

src/d_iwad.c

Picked from Woof's [#1831](https://github.com/fabiangreffrath/woof/pull/1831). I have a feeling that we have something missing here in Crispy, but for God's sake, let's just use orthodoxal IWADs with _«(c) id Software, 1993-1994»_ on title screens...

Add Unity and D1+D2 IWAD search folders

---

src/doom/m_menu.c
src/heretic/mn_menu.c
src/hexen/mn_menu.c
src/m_misc.c
src/strife/m_menu.c
src/strife/p_saveg.c

Fixes #1218. @fabiangreffrath, @rfomin, requesting your review, I'm not very familiar with `stat()` and not sure if `-1` is correct logics in this case, though it comes from [Woof logics](https://github.com/fabiangreffrath/woof/blob/387c0deb03d138632dde763ba21fe53ce9682704/src/mn_snapshot.c#L94).
Also, does `strfsav%d.ssg/name` correct for non Windows OSes?

Use `M_stat`, safe check and fix Strife save date/time

---

src/heretic/sb_bar.c

Fixes small shading issue on TrueColor + smooth diminished lighting, described in https://github.com/fabiangreffrath/crispy-doom/pull/1220#issuecomment-2345308283.

Heretic: fix for possible incorrect status bar shading in TrueColor

---

src/i_video.c

This fixes TrueColor's translucency blending, broken by recent `i_video.c` update, where all translucent pixels were drawn with solid black color, regardless of blending function and palette indexes. One remark:
* Ideally to don't have `int bpp`, it does not do anything, but needed for `SDL_PixelFormatEnumToMasks()` itself. A bit confusing, but now it's guarded by both `if (argbbuffer == NULL)` condition and `#ifdef CRISPY_TRUECOLOR` macro.

TrueColor: fix translucency blending

---

src/i_video.c

Done as suggested in comment https://github.com/fabiangreffrath/crispy-doom/commit/3201b93e38ead144f42d0779bee411a3a4455250#r146753091. This will help to get rid of unnecessary variables by turning them into macroses.

TrueColor: turn mask variables into macroses

---

src/hexen/g_game.c
src/hexen/mn_menu.c
src/hexen/sv_save.c

I was prompted to look into this code again after I saw [this post](https://www.doomworld.com/forum/post/2844695) on DW. I found an issue where saving a savefile on pages 1, 2 or 3 can potentially delete the save in the corresponding slot on page 2, 4 or 6 respectively. Not sure if this has any relation to the issue reported by the user on DW, but this bug should certainly be fixed regardless.

hexen: Fix wrong save being deleted

---

src/doom/g_game.c
src/heretic/g_game.c
src/hexen/g_game.c
src/m_config.c
src/setup/keyboard.c
src/setup/mouse.c

Related Issue:
Closes https://github.com/fabiangreffrath/crispy-doom/issues/1239
**Change Summary**
- Adding Quick Reverse Button (mouse and keyboard) to Heretic and Hexen.

Adding Quick Reverse Key to Hexen / Heretic

---

src/heretic/d_main.c
src/heretic/p_lights.c
src/heretic/p_saveg.c
src/heretic/p_setup.c
src/heretic/r_bsp.c
src/heretic/r_local.h
src/heretic/r_segs.c
src/heretic/r_things.c
src/setup/accessibility.c
src/setup/mainmenu.c

Related Issue:
Closes https://github.com/fabiangreffrath/crispy-doom/issues/1244
- Added Accessibility Option to Heretic Setup for Flickering Sector Lighting.
- Ported solution from Crispy-Doom for the actual disabling.
- Fixed issue having static strobe/glow/flash lightlevel != maxlight when loading save-files.
- Fixed issue having flickering-glitches in some level segment compositions (E1M1, E2M7).
Verified on E1M1 and E2M7 that no further flickering-glitches remain. Checked vanilla compatibility using 4 Demos (E1M1, E2M7, E4M1, E4M7), no deviation seen. No indication in the source-code found that lightlevel impacts player-detection by enemies.

Heretic: Adding a11y-Option - Flickering Sector Lighting

---

src/doom/p_extsaveg.c
src/doom/p_lights.c
src/doom/p_saveg.c
src/doom/r_bsp.c
src/doom/r_segs.c

- Fixed issue having static strobe/glow/flash lightlevel != maxlight when changing the option to disable sector flickering and loading a previously stored save-file.
- Fixed issue having flickering-glitches in some levels when it should be disabled.
Verified on Doom1 - E1M5 and E2M4 & Doom2 Lvl 09 - no further flickering-glitches seen. Checked vanilla compatibility using 3 regular Demos (start of maps Doom2 Lvl 02, 05, 24) and 2 Demos loading from savegames (Doom 2 LVL 05), no deviation seen. No indication in the source-code found that lightlevel impacts player-detection by enemies.

Doom: a11y Flickering Option Improvements

---

src/doom/p_extsaveg.c
src/doom/p_lights.c
src/doom/p_saveg.c
src/heretic/p_lights.c
src/heretic/p_saveg.c

Related Issue:
None - I can open one if required. 
Observed behavior:
In Heretic E1M6 (Hall with Dragonclaw) I still noticed flickering, even though it was disabled in the accessibility menu. After having a look at the map in Doom-Builder, there are trigger based actions to spawn strobelights for 4 linedefs refering the same sectors (97, 116). When a strobelight is spawned, the current sector lightlevel is stored in the maxlight. Since those spawns are not done simultaneously (the player triggers them by walking around), the second to forth spawn will take an already modified lightlevel and the maxlight will thus be "incorrect". Afterwards, they overwrite the sector lightlevel with their maxlights and thus reintroduce a strobing effect.
Expected behavior:
rlightlevel should be the highest …

Doom/Heretic: A11y Flickering - Correct Lightlevel in case of competing Strobe Thinkers

---

src/heretic/d_main.c
src/heretic/r_main.c
src/heretic/r_things.c
src/heretic/sb_bar.c
src/setup/accessibility.c

Related Issue:
None - I can open one if required. 
Added the following A11Y Features in Crispy-Heretic (to align with Crispy-Doom):
- Weapon Flash Lighting (also disables Torch Flickering)
- Weapon Flash Sprite
- Palette Changes
- Invulnerability Colormap
- Extra Lighting
The Blinking of diminishing Powers (Torch, Invul) remains active as an indicator for the player.

Heretic: Adding A11Y Features: Weapon Flash Lighting & Sprite, Palette Changes, Invul Colormap, Extra Lighting

---

src/v_video.c

Related Issue:
None
Adding a translucent and color-translated rendering function for Heretic/Hexen to be called optionally in DrawTLPatch. It is based upon drawtinttab, so the source-color remains the dominating one (for Palette), just corrected by the translation. This allows for transparent golden center-messages. 
Translated Palette Lookup example:
Translated True Color Blend example:

Hexen/Heretic: Support Color-Translation in V_DrawTLPatch

---

src/doom/p_user.c

Related Issue:
Closes https://github.com/fabiangreffrath/crispy-doom/issues/1259
This changes the behavior for diminishing powers when the invulnerability colormap is disabled in the A11Y settings. 
Previous Behavior:
If either or both Invul and Infrared Power was active, no blinking occurred when powers were diminishing, instead it transitioned to OFF or Invul->Infrared immediately.
New Behavior:
Every transition will results in a blinking to indicate that either Invul or Infrared is running out. This also is the case when both Invul and Infrared powers are present at the same time.

Doom: A11Y Disabled Invulnerability Colormap - Blinking of diminishing powers

---

src/hexen/ct_chat.c
src/hexen/h2_main.c
src/hexen/mn_menu.c
src/hexen/r_local.h
src/hexen/sb_bar.c

Related Issue:
None - I can open one if required. 
Similar to the Variations in Heretic, here now for Hexen:
- Adding Widescreen Version of Vanilla Fullscreen HUD
- Adding Transparent and non-widescreen Versions of the Crispy HUD
- Adding Transparent messages and icons based upon Crispy HUD selection

Hexen: Fullscreen HUD Variations

---

src/heretic/r_things.c

Related Commit:
https://github.com/fabiangreffrath/crispy-doom/pull/1260/commits/23d328181796d42666870c801a9c96f94162e4ef
**Change Description**
Its a bit of a late finding, but I saw today, that the replacement of the doomednum with the sprite name in the above mentioned commit has an undesired side-effect: The sprite (and also attack-states) are both present for the `MT_MUMMYLEADER` and `MT_MUMMYLEADERGHOST`, meaning that the ghost versions now also get a base-sprite drawn when the translucency-option is active. This is not intended, so I would like to hereby revert this change and use the unique identifier again to distinguish those otherwise similar enemy-types.

Heretic: Fix Translucency Option affecting MT_MUMMYLEADERGHOST

---

src/hexen/h2_main.c
src/hexen/p_anim.c
src/hexen/p_lights.c
src/hexen/p_local.h
src/hexen/p_setup.c
src/hexen/r_bsp.c
src/hexen/r_local.h
src/hexen/r_segs.c
src/hexen/r_things.c
src/hexen/sv_save.c
src/setup/accessibility.c
src/setup/mainmenu.c

Related PR for Heretic:
https://github.com/fabiangreffrath/crispy-doom/pull/1246
- Added Accessibility Option to Hexen Setup for Flickering Sector Lighting.
- Ported solution from Crispy-Heretic for the actual disabling.
- Lightning is also disabled by this option. 
Checked vanilla compatibility using 4 Demos (MAP 01 - 03, MAP 05), no deviation seen.

Hexen: Adding a11y-Option - Flickering Sector Lighting

---

src/heretic/r_things.c

This is a formal correction to assign a blendfunction for Truecolor when the MF_Translucent flag is present, which I missed when adding the transparency option for Heretic.
Since for Heretic, only I_BlendOverAltTinttab is assigned to this pointer anyways, it has worked also without this change in the past. However, it should be explicit for better understanding and future changes.

Heretic: Assign blendfunc when MF_Translucent is set

---

src/hexen/a_action.c
src/hexen/h2_main.c
src/hexen/h2def.h
src/hexen/info.c
src/hexen/mn_menu.c
src/hexen/r_things.c
src/m_config.c
src/setup/compatibility.c

Related Issue:
Closes https://github.com/fabiangreffrath/crispy-doom/issues/1276
- Adding Translucency Option to Hexen based upon Doom/Heretic solution
- Translucency supported for:
Option 1 (Projectiles):
- Own Weapon Projectiles
- Enemy Projectiles and Enemy Special Effects
- Various Environmental Things (Fireballs, Teleporter Stuff...)
Option 2 (vanilla Weapon flash)
- Weapon firing flashes to be transparent when using vanilla weapon sprites, by drawing transparent firing-frames over weapon idle-frames. This affects the following weapons: Mage Wand and Ultimate Weapon, Cleric Wand and Ultimate weapon. 
.. or both Options together.

Hexen: Adding Translucency Option

---

src/heretic/sb_bar.c
src/hexen/sb_bar.c

Related Issue:
None
The artifact selectbox should be always opaque when a transparent HUD is active. This allows for a better item selection in hasty moments, especially in Hexen.

Heretic/Hexen: Artifact selectbox always opaque

---

src/heretic/p_inter.c
src/hexen/p_inter.c
src/hexen/p_mobj.c

Related Issue:
None 
After playing through hexen, some minor translucency changes I would like to bring in:
- Hexen: Making ripperball explosion translucent
- Hexen/Heretic: Making artifact pickup effect translucent
- Hexen/Heretic: (Deathmatch) Making artifact & thing respawn effects translucent

Hexen/Heretic: Minor translucency changes

---

src/heretic/s_sound.c

Related Issue:
None 
After revisiting the option, I found that the reduction was slightly over-done and that the different reduction values per effect sounded weird when fighting certain enemies. That is why I would like to increase the sound volume slightly by half a unit and simplifiy it. I should have given it more time initially 😉.

Heretic: Further optimizing weapon sound leveling

---

src/heretic/am_map.c
src/heretic/d_main.c
src/hexen/am_map.c
src/hexen/h2_main.c

Related Issue:
None 
I noticed a bug that can cause the numbers to be displayed translucent in the automap statusbar sporadically (timing-dependend), when a translucent hud is active:
Moving the check for the translucency directly into AM_Drawer resolved the issue, however I couldn't pin point the root-cause directly. I presume the R_RenderPlayerView Updates were causing it.

Heretic/Hexen: Fix translucent numbers in Automap-Statusbar

---

src/hexen/info.c

Related Issue:
None 
While playing Hexen DKDC, I noticed that the Wyvern fire on the ground was not yet translucent with the option enabled. I would like to hereby change that.
Sorry for bringing up yet another translucency finding. One day, I hopefully caught them all. 😉

Hexen: Translucent Wyvern explosion

---

src/hexen/info.c
src/hexen/p_enemy.c

Related Issue:
None 
For some reason, I just recently noticed that the Heresiarch mana cubes do detach upon his death, bounce and explode. Them being translucent makes it hard to see where they land and can cause confusing player deaths. With this change they remain opaque now and I did the same for the shield-bits flying around, to be consitent.
- Sorcball1-3 always opaque until explosion
- SORCFX2 (shield) always opaque for consitency reasons

Hexen: heresiarch opaque mana cubes & shield

---

src/doom/f_finale.c

Short explanation: fixes [this issue](https://www.doomworld.com/forum/post/2919478).
Long explanation: rust2.wad replaces some of the hu_font characters with "almost fullscreen" patches. These patches have carefully chosen top and left offsets to allow them to display correctly based on what the current text position is. (Pretty clever!) To allow this trick to function properly, account for the top offset when checking if a patch is going to be drawn off-screen vertically.
If you want to see this for yourself run: `crispy-doom -iwad doom.wad -gameversion 1.666 -file rust2.wad -warp 2 8`
and then use the `tntem` cheat to quickly end the level and advance up the finale. Be sure to wait until the end.

doom: Include top offset in finale text check

---

src/setup/accessibility.c
src/setup/mainmenu.c
src/strife/d_main.c
src/strife/p_enemy.c
src/strife/p_lights.c
src/strife/p_saveg.c
src/strife/p_setup.c
src/strife/r_bsp.c
src/strife/r_defs.h
src/strife/r_segs.c
src/strife/r_things.c

Related Issue:
none
Here we go again 😉: I also want to bring translucency and A11Y Features to Strife and starting with this, I added the A11Y Flickering option in the same style as for the remaining games. 
I verified it with a few demos against chocolate-strife on Map 06, 09, 15, 25, 30.

Strife: Adding A11Y Flickering

---

src/heretic/s_sound.c

Related Issue:
None 
Sorry for bringing this up again, but after revisiting the feature, I still think that the reduction was a tiny bit too much. With this, I would like to remove the fraction and "only" lower it by a multiple of 3.

Heretic: Yet another fine tuning of weapon sound leveling

---

src/doom/r_data.c
src/doom/r_data.h
src/doom/r_plane.c

Pulled from Woof: https://github.com/fabiangreffrath/woof/commit/d8f50be53e2d121ea42f8446fffedd6ef28901a3 and https://github.com/fabiangreffrath/woof/pull/2303
Testing with 386px texture:

Add support for non-power-of-2 textures

---

src/doom/d_pwad.c
src/doom/f_finale.c
src/doom/g_game.c
src/doom/m_menu.c
src/doom/p_setup.c
src/doom/wi_stuff.c

Related PR:
https://github.com/fabiangreffrath/crispy-doom/pull/1311
- Allow secret level to work correctly in kex sequence (TEETH SecretExit -> Bad Dreams -> Bloodsea Keep)
- Adaption of GotoNextLevel for kex sequence
- Support of masterlevels.wad kex skyboxes
- Fixing bug having wrong skyboxes when switching between gamemissions

Doom: masterlevels.wad kex support secret level & skyboxes

---

src/heretic/g_game.c

This PR adds support for sky textures from episodes 4 and 5 of the H+H re-release; the episode 6 texture is also included for episode six and beyond.

Heretic: add support for H+H sky textures

---

src/heretic/p_spec.c

This pull request does not add `ANIMDEFS` support to Heretic, nor does it add support for Kex engine specifics. The animations and their timings, however, are taken directly from the H+H `ANIMDEFS` lump, descriptions are my own, just for consistency.
Test map: [hh_htic_liquids.zip](https://github.com/user-attachments/files/21721313/hh_htic_liquids.zip)
Notes on the test map:
* In Kex, flats in cycles **II** and **III** are not animated, whereas in our case any cycle texture is animated.
* Flats other than cycle **I** do not produce splashes. This behavior is already accounted for in the original Heretic.
* Blood flats do not produce splashes and do not create the sinking-into-liquid effect. Sadly.

Heretic: add support for H+H animated textures

---

src/doom/r_data.c
src/doom/r_data.h
src/doom/r_segs.c
src/heretic/r_data.c
src/hexen/r_data.c
src/strife/r_data.c

The H+H re-release contains a good handful of new textures that do not fall on the power-of-2 scale (96px, 160px, 192px, etc) so I went ahead and updated all 4 games to include support for it.

Enhanced support for non-power-of-2 wide textures -- Heretic, Hexen & Strife

---

src/hexen/sb_bar.c

Related Issue:
None
For some reason, the kex hexen iwad changed lumpnum sequences when it comes to weapon pieces / lifegems.
With this change, both .wads shall be respected by explicitly mapping the pieces / lifegems per class.

Hexen: support of kex iwad weapon pieces & lifegems
